package enums;

public enum TypeGraphic {

    NONE, GRAPH2D, GRAPHIMPLICIT2D, GRAPHIMPLICIT3D, GRAPH3D, GRAPHCURVE2D, GRAPHCURVE3D, 
    GRAPHPOLAR, GRAPHCYLINDRCAL, GRAPHSPHERICAL, GRAPHSURFACE, VECTORFIELD2D, VECTORFIELD3D;

}
